name: CI

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    container: dimo414/ci-profilegem
    strategy:
      matrix:
        bash-version: [bash-5, bash-4, bash-3]

    steps:
    - uses: actions/checkout@v2
    # TODO add unit tests
    #- name: "Unit Tests - ${{ matrix.bash-version }}"
    #  run: bats test
    - name: "ProfileGem Tests - ${{ matrix.bash-version }}"
      run: ${{ matrix.bash-version }} /pgem_test/pgem_test.sh

  ShellCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: ShellCheck
        uses: docker://koalaman/shellcheck-alpine
        with:
          entrypoint: sh
          args: -c "find . -name '*.sh' -exec shellcheck --shell=bash --exclude=1090,2034 {} +"